export default [
  {
    title: 'User-Generated AI Avatars',
    description: 'Choose one of the AI Avatars generated by our Creators.',
    text: 'Select your favorite User-generated AI Avatar and click Select and Continue.',
    header: 'Choose an AI Avatar and click Select and Continue',
    imageSrc: require('../../assets/avatar2.jpeg'),
    mode: 'user-generated'
  }
  // {
  //   title: 'Tokenized AI Avatars',
  //   description: 'Create digital media with a licensed AI Avatar, powering the next-generation of Virtual Economies.',
  //   text: 'Unlock a tokenized AI Avatar to create licensed digital media.',
  //   header: 'Choose an AI Avatar and click Unlock via MetaMask',
  //   imageSrc: require('../../assets/avatar3.jpeg'),
  //   mode: 'tokenized'
  // },
  // {
  //   title: 'Create Your Own AI Avatar',
  //   description: 'We are gradually opening up access to Creators and Enterprises that want to create AI Avatars.',
  //   text: 'Please upload an image that matches the description of a headshot, or passport photo.',
  //   message: 'Please select one of the plans that best suits your needs:',
  //   header: 'Choose a plan to create your own AI Avatar',
  //   imageSrc: require('../../assets/avatar4.png'),
  //   mode: 'custom'
  // }
];
