export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const SET_DRAWER = 'SET_DRAWER';

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const SET_LOGIN_MODAL = 'SET_LOGIN_MODAL';
export const OPEN_SIGNUP_MODAL = 'OPEN_SIGNUP_MODAL';
export const SET_SIGNUP_MODAL = 'SET_SIGNUP_MODAL';
export const OPEN_FORGOT_PASSWORD_MODAL = 'OPEN_FORGOT_PASSWORD_MODAL';
export const SET_FORGOT_PASSWORD_MODAL = 'SET_FORGOT_PASSWORD_MODAL';
export const CLOSE_AUTH_MODAL = 'CLOSE_AUTH_MODAL';
export const SET_AUTH_MODAL = 'SET_AUTH_MODAL';

export const SELECT_VIDEO_ID = 'SELECT_VIDEO_ID';
export const SET_VIDEO_ID = 'SET_VIDEO_ID';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const UPDATE_RENDER_DATA = 'UPDATE_RENDER_DATA';
export const SET_RENDER_DATA = 'SET_RENDER_DATA';

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';

export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';

export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST';
export const GOOGLE_SIGNUP_REQUEST = 'GOOGLE_SIGNUP_REQUEST';

export const UPDATE_CREDIT = 'UPDATE_CREDIT';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_RESPONSE = 'CHANGE_PASSWORD_RESPONSE';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_RESPONSE = 'FORGOT_PASSWORD_RESPONSE';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_RESPONSE = 'RESET_PASSWORD_RESPONSE';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_RESPONSE = 'UPDATE_PROFILE_RESPONSE';

export const VERIFY_REQUEST = 'VERIFY_REQUEST';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_ERROR = 'VERIFY_ERROR';

export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_RESPONSE = 'GET_JOBS_RESPONSE';
export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_RESPONSE = 'CREATE_JOB_RESPONSE';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';
export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_RESPONSE = 'UPDATE_JOB_RESPONSE';
export const GET_JOB = 'GET_JOB';
export const GET_JOB_RESPONSE = 'GET_JOB_RESPONSE';
export const DELETE_JOB = 'DELETE_JOB';
export const DELETE_JOB_RESPONSE = 'DELETE_JOB_RESPONSE';
export const SET_CURRENT_JOB = 'SET_CURRENT_JOB';

export const GET_PUBLIC_AVATARS = 'GET_PUBLIC_AVATARS';
export const GET_PUBLIC_AVATARS_RESPONSE = 'GET_PUBLIC_AVATARS_RESPONSE';
export const GET_USER_AVATARS = 'GET_USER_AVATARS';
export const GET_USER_AVATARS_RESPONSE = 'GET_USER_AVATARS_RESPONSE';

export const GET_PUBLIC_CATEGORIES = 'GET_PUBLIC_CATEGORIES';
export const GET_PUBLIC_CATEGORIES_RESPONSE = 'GET_PUBLIC_CATEGORIES_RESPONSE';
export const GET_USER_CATEGORIES = 'GET_USER_CATEGORIES';
export const GET_USER_CATEGORIES_RESPONSE = 'GET_USER_CATEGORIES_RESPONSE';
